FROM node:14-alpine

RUN apk --no-cache add git \
  && git clone https://github.com/MCSManager/MCSManager-Web-Production /data/mcsmanager/web --depth=1 \
  && cd /data/mcsmanager/web && npm i --production \
  && mkdir -p /data/mcsmanager/web/data

ENV TZ=Asia/Shanghai

VOLUME [ "/data/mcsmanager/web/data" ]

EXPOSE 23333

WORKDIR /data/mcsmanager/web

ENTRYPOINT [ "node", "app.js" ]
